version: "3.7"
services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    ports:
      - "5370:5370"
  postgres:
    image: postgres:15.4
    container_name: db-pg
    command: -p 1221
    expose:
        - 1221
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB}, ${POSTGRES_DB_TEST}
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
  src:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    command: bash -c "export PYTHONPATH=$(pwd)/src &&
      alembic -c src/alembic.ini upgrade a359a29e7732 &&
      python -m src.app.service"
    ports:
      - 8080:8080
    volumes:
      - ./:/opt/pysetup/
    depends_on:
      - redis
      - postgres
